"""Swappable storage interfaces for run-state persistence and artifact I/O.

These protocols define the surface area that must be implemented to swap the
default SQLite + local-filesystem backend for a cloud backend (e.g. Cloudflare
D1 + R2).  Current concrete implementations are:

    SQLiteRunStore   = RunStore      (mechanistic_agent.core.db)
    LocalArtifactStore               (below)

Dependency-inversion note
-------------------------
All coordinator and API code currently depends on RunStore directly.  The
Protocol classes here serve as the canonical interface contract: new cloud
adapters must implement them, and call-site type annotations should reference
these protocols rather than the concrete classes.  This refactor does NOT
change any runtime behaviour — it is purely a type-level and structural
improvement.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List, Optional

try:
    from typing import Protocol, runtime_checkable
except ImportError:  # Python < 3.8
    from typing_extensions import Protocol, runtime_checkable  # type: ignore[assignment]


# ---------------------------------------------------------------------------
# RunStateStore — run lifecycle, events, step outputs, evaluations, etc.
# ---------------------------------------------------------------------------

@runtime_checkable
class RunStateStore(Protocol):
    """Protocol satisfied by RunStore (SQLite) and future cloud adapters."""

    # --- Run lifecycle ---
    def create_run(self, run_id: str, /, **kwargs: Any) -> None: ...
    def get_run_row(self, run_id: str) -> Optional[Dict[str, Any]]: ...
    def set_run_status(self, run_id: str, status: str) -> None: ...
    def delete_run(self, run_id: str) -> bool: ...
    def update_run_config(self, run_id: str, config: Dict[str, Any]) -> None: ...

    # --- Events ---
    def append_event(self, run_id: str, /, **kwargs: Any) -> None: ...
    def list_events(self, run_id: str, *, after_seq: int = 0, limit: int = 500) -> List[Dict[str, Any]]: ...

    # --- Step outputs ---
    def record_step_output(self, run_id: str, /, **kwargs: Any) -> None: ...
    def list_step_outputs(self, run_id: str) -> List[Dict[str, Any]]: ...

    # --- Trace records ---
    def add_trace_record(self, /, **kwargs: Any) -> str: ...
    def list_trace_records(self, /, **kwargs: Any) -> List[Dict[str, Any]]: ...
    def get_trace_record(self, trace_id: str) -> Optional[Dict[str, Any]]: ...
    def approve_trace_record(self, trace_id: str, /, **kwargs: Any) -> None: ...

    # --- Prompt / model versioning ---
    def upsert_prompt_versions(self, prompts: List[Dict[str, Any]]) -> Dict[str, str]: ...
    def upsert_model_version(self, /, **kwargs: Any) -> str: ...
    def resolve_run_step_prompt_id(self, /, **kwargs: Any) -> Optional[str]: ...
    def bind_run_step_prompt(self, /, **kwargs: Any) -> None: ...
    def list_run_step_prompts(self, run_id: str) -> List[Dict[str, Any]]: ...
    def list_prompt_versions(self, /, **kwargs: Any) -> List[Dict[str, Any]]: ...
    def get_prompt_version(self, prompt_version_id: str) -> Optional[Dict[str, Any]]: ...
    def get_model_version(self, model_version_id: str) -> Optional[Dict[str, Any]]: ...

    # --- Eval sets / runs ---
    def add_eval_set(self, /, **kwargs: Any) -> str: ...
    def list_eval_sets(self, /, **kwargs: Any) -> List[Dict[str, Any]]: ...
    def get_eval_set(self, eval_set_id: str) -> Optional[Dict[str, Any]]: ...
    def list_eval_set_cases(self, eval_set_id: str) -> List[Dict[str, Any]]: ...
    def create_eval_run(self, /, **kwargs: Any) -> str: ...
    def set_eval_run_status(self, eval_run_id: str, status: str) -> None: ...
    def record_eval_run_result(self, /, **kwargs: Any) -> None: ...
    def list_eval_run_results(self, eval_run_id: str) -> List[Dict[str, Any]]: ...
    def list_eval_runs(self, eval_set_id: Optional[str] = None) -> List[Dict[str, Any]]: ...
    def get_eval_run(self, eval_run_id: str) -> Optional[Dict[str, Any]]: ...
    def leaderboard(self, eval_set_id: str, *, limit: int = 20) -> List[Dict[str, Any]]: ...

    # --- Verification ---
    def create_verification_job(self, /, **kwargs: Any) -> str: ...
    def update_verification_job_progress(self, /, **kwargs: Any) -> None: ...
    def complete_verification_job(self, /, **kwargs: Any) -> None: ...
    def get_verification_job(self, job_id: str) -> Optional[Dict[str, Any]]: ...
    def list_verification_jobs(self, limit: int = 20) -> List[Dict[str, Any]]: ...
    def upsert_verification_result(self, /, **kwargs: Any) -> None: ...
    def get_verified_step_models(self, /, **kwargs: Any) -> List[Dict[str, Any]]: ...
    def list_verification_history(self, /, **kwargs: Any) -> List[Dict[str, Any]]: ...

    # --- Misc ---
    def record_assets(self, assets: List[Dict[str, Any]]) -> None: ...
    def record_evaluation(self, /, **kwargs: Any) -> str: ...
    def get_latest_evaluation(self, run_id: str) -> Optional[Dict[str, Any]]: ...
    def list_evaluations(self, run_id: str) -> List[Dict[str, Any]]: ...
    def get_run_snapshot(self, run_id: str) -> Optional[Dict[str, Any]]: ...
    def get_run_cost_summary(self, run_id: str) -> Dict[str, Any]: ...
    def add_few_shot_example(self, /, **kwargs: Any) -> str: ...
    def list_few_shot_examples(self, /, **kwargs: Any) -> List[Dict[str, Any]]: ...
    def record_feedback(self, /, **kwargs: Any) -> None: ...
    def list_feedback(self, run_id: str) -> List[Dict[str, Any]]: ...
    def add_memory_item(self, /, **kwargs: Any) -> str: ...
    def list_memory_items(self, /, **kwargs: Any) -> List[Dict[str, Any]]: ...
    def create_run_pause(self, /, **kwargs: Any) -> str: ...
    def resolve_run_pause(self, /, **kwargs: Any) -> None: ...
    def get_latest_run_pause(self, run_id: str) -> Optional[Dict[str, Any]]: ...
    def create_ralph_attempt(self, /, **kwargs: Any) -> str: ...
    def complete_ralph_attempt(self, /, **kwargs: Any) -> None: ...
    def list_ralph_attempts(self, parent_run_id: str) -> List[Dict[str, Any]]: ...
    def record_ralph_vote(self, /, **kwargs: Any) -> None: ...
    def list_ralph_votes(self, run_id: str) -> List[Dict[str, Any]]: ...
    def record_arrow_push_annotation(self, /, **kwargs: Any) -> None: ...
    def list_arrow_push_annotations(self, /, **kwargs: Any) -> List[Dict[str, Any]]: ...
    def record_verification_decision(self, /, **kwargs: Any) -> None: ...
    def update_step_acceptance(self, /, **kwargs: Any) -> None: ...
    def unaccepted_verified_steps(self, run_id: str) -> List[Dict[str, Any]]: ...
    def record_curation_export(self, /, **kwargs: Any) -> None: ...
    def list_curation_exports(self, /, **kwargs: Any) -> List[Dict[str, Any]]: ...
    def queue_curriculum_release(self, /, **kwargs: Any) -> str: ...
    def list_curriculum_releases(self, /, **kwargs: Any) -> List[Dict[str, Any]]: ...
    def get_curriculum_release(self, queue_id: str) -> Optional[Dict[str, Any]]: ...
    def update_curriculum_release(self, /, **kwargs: Any) -> None: ...
    def record_curriculum_checkpoint(self, /, **kwargs: Any) -> str: ...
    def list_curriculum_checkpoints(self, /, **kwargs: Any) -> List[Dict[str, Any]]: ...
    def get_curriculum_checkpoint(self, checkpoint_id: str) -> Optional[Dict[str, Any]]: ...
    def list_eval_run_results_many(self, eval_run_ids: List[str]) -> Dict[str, List[Dict[str, Any]]]: ...
    def seed_simulated_leaderboard(self, /, **kwargs: Any) -> None: ...
    def delete_simulated_leaderboard_rows(self, eval_set_id: str) -> Dict[str, Any]: ...


# ---------------------------------------------------------------------------
# ArtifactStore — blob / trace file I/O
# ---------------------------------------------------------------------------

@runtime_checkable
class ArtifactStore(Protocol):
    """Protocol for reading and writing run artifacts (traces, evidence, etc.).

    The local implementation uses the filesystem under traces_root().
    A cloud implementation would use e.g. Cloudflare R2 or S3.
    """

    def write_artifact(self, relative_path: str, content: bytes) -> Path:
        """Write *content* to *relative_path* (relative to the artifact root).

        Returns the concrete Path (or a mock Path for remote stores).
        """
        ...

    def read_artifact(self, relative_path: str) -> Optional[bytes]:
        """Return the bytes at *relative_path*, or None if not found."""
        ...

    def artifact_path(self, relative_path: str) -> Path:
        """Return the absolute Path for *relative_path* (for callers that still
        need a local Path, e.g. to pass to subprocess tools).

        Remote implementations may materialise the file locally on demand.
        """
        ...


# ---------------------------------------------------------------------------
# Default (local) implementations
# ---------------------------------------------------------------------------

# SQLiteRunStore is the existing RunStore — no changes to that class needed.
from mechanistic_agent.core.db import RunStore as SQLiteRunStore  # noqa: E402


class LocalArtifactStore:
    """Filesystem-backed ArtifactStore using the configured traces root."""

    def __init__(self, base_dir: Path) -> None:
        from mechanistic_agent.prompt_assets import traces_root
        self._root: Path = traces_root(base_dir)

    def write_artifact(self, relative_path: str, content: bytes) -> Path:
        dest = self._root / relative_path
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(content)
        return dest

    def read_artifact(self, relative_path: str) -> Optional[bytes]:
        p = self._root / relative_path
        if not p.exists():
            return None
        return p.read_bytes()

    def artifact_path(self, relative_path: str) -> Path:
        return self._root / relative_path
